//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Talker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class HardareIntegration : global::System.Configuration.ApplicationSettingsBase {
        
        private static HardareIntegration defaultInstance = ((HardareIntegration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HardareIntegration())));
        
        public static HardareIntegration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Active_COM_Port {
            get {
                return ((string)(this["Active_COM_Port"]));
            }
            set {
                this["Active_COM_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string Roku_IP {
            get {
                return ((string)(this["Roku_IP"]));
            }
            set {
                this["Roku_IP"] = value;
            }
        }
    }
}
