//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Talker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Child_Talker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;profile name=&quot;Test Profile&quot;&gt;
        ///   &lt;items&gt;
        ///      &lt;item name=&quot;Kris&quot; image=&quot;../../Resources/kris.jpg&quot; /&gt;
        ///      &lt;item name=&quot;Also Kris&quot; image=&quot;../../Resources/kris.jpg&quot; /&gt;
        ///      &lt;item name=&quot;This might be Kris&quot; image=&quot;../../Resources/kris.jpg&quot; /&gt;
        ///      &lt;item name=&quot;Mr. Dr. Professor. Kris Schindler MD.&quot; image=&quot;../../Resources/kris.jpg&quot; /&gt;
        ///      &lt;item name=&quot;Need more Kris&quot; image=&quot;../../Resources/kris.jpg&quot; /&gt;
        ///      &lt;item name=&quot;Can&apos;t stop the Kris&quot; image=&quot;../../Resources [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Item1&quot;:&quot;2019-03-11T15:09:57.6440494-04:00&quot;,&quot;Item2&quot;:&quot;HELLO&quot;},{&quot;Item1&quot;:&quot;2019-03-11T15:10:04.579664-04:00&quot;,&quot;Item2&quot;:&quot;MY NAME IS SAM&quot;},{&quot;Item1&quot;:&quot;2019-03-11T15:11:13.1550664-04:00&quot;,&quot;Item2&quot;:&quot;I GOT THE SAVE FEATURE WORKING&quot;},{&quot;Item1&quot;:&quot;2019-03-11T17:54:59.1929236-04:00&quot;,&quot;Item2&quot;:&quot;Hello World!&quot;},{&quot;Item1&quot;:&quot;2019-03-11T17:56:35.8291765-04:00&quot;,&quot;Item2&quot;:&quot;Hello World Everyone!&quot;},{&quot;Item1&quot;:&quot;2019-03-11T17:56:45.533234-04:00&quot;,&quot;Item2&quot;:&quot;HI&quot;},{&quot;Item1&quot;:&quot;2019-03-11T17:56:50.0779903-04:00&quot;,&quot;Item2&quot;:&quot;How are you?&quot;},{&quot;Item1&quot;:&quot;2019-03- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpeechHistory {
            get {
                return ResourceManager.GetString("SpeechHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;hello&quot;:12,&quot;world&quot;:1,&quot;hi&quot;:3,&quot;hey&quot;:3,&quot;there&quot;:1,&quot;howdy&quot;:4,&quot;my&quot;:3,&quot;name&quot;:3,&quot;is&quot;:3,&quot;sam&quot;:3,&quot;free&quot;:3,&quot;so&quot;:1,&quot;oh&quot;:1,&quot;no&quot;:1}.
        /// </summary>
        internal static string WordCount {
            get {
                return ResourceManager.GetString("WordCount", resourceCulture);
            }
        }
    }
}
