//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Talker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.Color BackgroundHighlighted {
            get {
                return ((global::System.Windows.Media.Color)(this["BackgroundHighlighted"]));
            }
            set {
                this["BackgroundHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color BackgroundBase {
            get {
                return ((global::System.Windows.Media.Color)(this["BackgroundBase"]));
            }
            set {
                this["BackgroundBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999900")]
        public global::System.Windows.Media.Color BackgroundMouseHover {
            get {
                return ((global::System.Windows.Media.Color)(this["BackgroundMouseHover"]));
            }
            set {
                this["BackgroundMouseHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color BackgroundEventInner {
            get {
                return ((global::System.Windows.Media.Color)(this["BackgroundEventInner"]));
            }
            set {
                this["BackgroundEventInner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999900")]
        public global::System.Windows.Media.Color BackgroundEventOuter {
            get {
                return ((global::System.Windows.Media.Color)(this["BackgroundEventOuter"]));
            }
            set {
                this["BackgroundEventOuter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFC000C0")]
        public global::System.Windows.Media.Color ForegroundHighlighted {
            get {
                return ((global::System.Windows.Media.Color)(this["ForegroundHighlighted"]));
            }
            set {
                this["ForegroundHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00CFF3")]
        public global::System.Windows.Media.Color ForegroundBase {
            get {
                return ((global::System.Windows.Media.Color)(this["ForegroundBase"]));
            }
            set {
                this["ForegroundBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF700070")]
        public global::System.Windows.Media.Color ForegroundMouseOver {
            get {
                return ((global::System.Windows.Media.Color)(this["ForegroundMouseOver"]));
            }
            set {
                this["ForegroundMouseOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color BorderColorBase {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColorBase"]));
            }
            set {
                this["BorderColorBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double AutoscanTimerSpeed {
            get {
                return ((double)(this["AutoscanTimerSpeed"]));
            }
            set {
                this["AutoscanTimerSpeed"] = value;
            }
        }
    }
}
