//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Talker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Page_Background {
            get {
                return ((global::System.Windows.Media.Color)(this["Page_Background"]));
            }
            set {
                this["Page_Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public double Scan_Speed {
            get {
                return ((double)(this["Scan_Speed"]));
            }
            set {
                this["Scan_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.Color Background_Highlighted {
            get {
                return ((global::System.Windows.Media.Color)(this["Background_Highlighted"]));
            }
            set {
                this["Background_Highlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Background_Base {
            get {
                return ((global::System.Windows.Media.Color)(this["Background_Base"]));
            }
            set {
                this["Background_Base"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999900")]
        public global::System.Windows.Media.Color Background_MouseHover {
            get {
                return ((global::System.Windows.Media.Color)(this["Background_MouseHover"]));
            }
            set {
                this["Background_MouseHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Background_EventInner {
            get {
                return ((global::System.Windows.Media.Color)(this["Background_EventInner"]));
            }
            set {
                this["Background_EventInner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999900")]
        public global::System.Windows.Media.Color Background_EventOuter {
            get {
                return ((global::System.Windows.Media.Color)(this["Background_EventOuter"]));
            }
            set {
                this["Background_EventOuter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFC000C0")]
        public global::System.Windows.Media.Color Foreground_Highlighted {
            get {
                return ((global::System.Windows.Media.Color)(this["Foreground_Highlighted"]));
            }
            set {
                this["Foreground_Highlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00CFF3")]
        public global::System.Windows.Media.Color Foreground_Base {
            get {
                return ((global::System.Windows.Media.Color)(this["Foreground_Base"]));
            }
            set {
                this["Foreground_Base"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF700070")]
        public global::System.Windows.Media.Color Foreground_MouseOver {
            get {
                return ((global::System.Windows.Media.Color)(this["Foreground_MouseOver"]));
            }
            set {
                this["Foreground_MouseOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color BorderColor_Base {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColor_Base"]));
            }
            set {
                this["BorderColor_Base"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color BorderColor_Highlighted {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColor_Highlighted"]));
            }
            set {
                this["BorderColor_Highlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoscanEnabled {
            get {
                return ((bool)(this["AutoscanEnabled"]));
            }
            set {
                this["AutoscanEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF666666")]
        public global::System.Windows.Media.Color Page_SecondaryBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["Page_SecondaryBackground"]));
            }
            set {
                this["Page_SecondaryBackground"] = value;
            }
        }
    }
}
